// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzAVhgq9w08MW_IdxRQ1_6RJJAqtY5cM8',
    appId: '1:297316646050:web:fd7430590966ad1ce4abfb',
    messagingSenderId: '297316646050',
    projectId: 'flutter-ecommerce-5ecaf',
    authDomain: 'flutter-ecommerce-5ecaf.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-5ecaf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR9NP4qdiKYm8BzBSFkdnexNDnf8SNsKA',
    appId: '1:297316646050:android:f929b73f2b0387aae4abfb',
    messagingSenderId: '297316646050',
    projectId: 'flutter-ecommerce-5ecaf',
    storageBucket: 'flutter-ecommerce-5ecaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzU23INR9TXzIX1zeKcJDiZK9pwDNrs10',
    appId: '1:297316646050:ios:418b5e6a077fa58ae4abfb',
    messagingSenderId: '297316646050',
    projectId: 'flutter-ecommerce-5ecaf',
    storageBucket: 'flutter-ecommerce-5ecaf.appspot.com',
    iosClientId: '297316646050-g3jfsukvt20dn0c8hqk0p6ob38ffjjkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzU23INR9TXzIX1zeKcJDiZK9pwDNrs10',
    appId: '1:297316646050:ios:418b5e6a077fa58ae4abfb',
    messagingSenderId: '297316646050',
    projectId: 'flutter-ecommerce-5ecaf',
    storageBucket: 'flutter-ecommerce-5ecaf.appspot.com',
    iosClientId: '297316646050-g3jfsukvt20dn0c8hqk0p6ob38ffjjkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );
}
