// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkIUOnbNSV5nwX1sK2K811Ic_gnu7qZpM',
    appId: '1:1077324787021:web:c6ca61d0adfcbbb503db04',
    messagingSenderId: '1077324787021',
    projectId: 'note-fire-820a9',
    authDomain: 'note-fire-820a9.firebaseapp.com',
    storageBucket: 'note-fire-820a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeUBap7ZTFHD-xO0TDTrLZyt-kbqSGvDA',
    appId: '1:1077324787021:android:8995781f83090a7e03db04',
    messagingSenderId: '1077324787021',
    projectId: 'note-fire-820a9',
    storageBucket: 'note-fire-820a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ0igoFxT2dwMuwc_KCwLtXn5OV9TCVic',
    appId: '1:1077324787021:ios:41eabc2d6e6a988303db04',
    messagingSenderId: '1077324787021',
    projectId: 'note-fire-820a9',
    storageBucket: 'note-fire-820a9.appspot.com',
    iosClientId: '1077324787021-3va1epv3vebr67k782b0plcfodc7fovi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ0igoFxT2dwMuwc_KCwLtXn5OV9TCVic',
    appId: '1:1077324787021:ios:41eabc2d6e6a988303db04',
    messagingSenderId: '1077324787021',
    projectId: 'note-fire-820a9',
    storageBucket: 'note-fire-820a9.appspot.com',
    iosClientId: '1077324787021-3va1epv3vebr67k782b0plcfodc7fovi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
